### PR TITLE
Fixes #2. Added AboutUS page UI.

### LINKED ISSUE #2: Edit the About Us page.
In about us section create a section which introduces a member of team. You can use your own creativity to create the it. 
As a template you can refer this but it is not limited to it.
aboutus3

### PR DESCRIPTION
**Pull request by NitinNair89**
Hi @JigmeT123 

Please review my PR and let me know if any changes required.

I have added placeholder SVGs from the below link:
https://www.svgrepo.com/vectors/avatar/filled/1

Regards,
Nitin

### CODE REVIEW

**Comment by JigmeT123** [comment]
Job well done @NitinNair89. Thank you for the contribution. The code looks really clean. 
Feel free to contribute more if you want.

**Comment by NitinNair89** [comment]
> Job well done @NitinNair89. Thank you for the contribution. The code looks really clean. Feel free to contribute more if you want.

Thank you so much @JigmeT123! Sure, please assign me tasks or let me know which ones I can work on. 🙂

**Comment by JigmeT123** [comment]
> > Job well done @NitinNair89. Thank you for the contribution. The code looks really clean. Feel free to contribute more if you want.
> 
> Thank you so much @JigmeT123! Sure, please assign me tasks or let me know which ones I can work on. 🙂

How about footer for the website? Currently doesn't have a good one

**Comment by NitinNair89** [comment]
Sure @JigmeT123. Please assign it to me, if no one else is working on it. If you have any reference UI, that would be great. Also, the About US page needs to be updated to replace dummy data with actual data.

**Pull request merged**
