### PR TITLE
Fixes #3. Revamped contactus page UI.

### LINKED ISSUE #3: Revamp - Contact Us page.
You can beautify or make the current Contact Us page better. 
The creativity is all yours.

### PR DESCRIPTION
**Pull request by NitinNair89**
Hi @JigmeT123 
Please review and let me know if any changes are required.

**Screenshot**
ContactUs_screenshot

### CODE REVIEW

**Comment by JigmeT123** [comment]
Hey @NitinNair89 everything looks great. Can you please add an email validation. Right now there is no email validation when given an invalid address.

**Review by jigmetnamgyal — CHANGES_REQUESTED** [review]
Hey @NitinNair89 everything looks great. Can you please add an email validation. Right now there is no email validation when given an invalid address.

**Comment by NitinNair89** [comment]
Hi @JigmeT123 
Please review and accept PR if everything looks good to you.

**Comment by NitinNair89** [comment]
> Hey @NitinNair89 everything looks great. Can you please add an email validation. Right now there is no email validation when given an invalid address.

I've added email validation. Please review once.

Email regex pattern source:
https://www.itsolutionstuff.com/post/react-email-validation-exampleexample.html

Please review and accept PR if everything looks good to you.

**Comment by JigmeT123** [comment]
Hey sorry for the delay. just done reviewing the code. Looks good. Thank you for the contribution @NitinNair89

**Comment by NitinNair89** [comment]
> Hey sorry for the delay. just done reviewing the code. Looks good. Thank you for the contribution @NitinNair89

No problem, thank you so much. Please let me know if there are any issues that I can work on 🙂

**Comment by NitinNair89** [comment]
@JigmeT123  Could you also please add hacktoberfest-accepeted label to this PR?

**Pull request merged**
