### PR TITLE
Contact us updated with background and new styles

### PR DESCRIPTION
**Pull request by DADDY-DOUBLESHOT**
Hey @JigmeT123 I made few changes please review my PR

### CODE REVIEW

**Comment by JigmeT123** [comment]
You did'nt do any significant changes to the project except for background changes. Please try to work on it more so that I can approve your pr. Thank you.

Looking forward to seeing the changes

**Review by JigmeT123 — CHANGES_REQUESTED** [review]
You did'nt do any significant changes to the project except for background changes. Please try to work on it more so that I can approve your pr. Thank you.

Looking forward to seeing the changes

**Comment by DADDY-DOUBLESHOT** [comment]
Hey @JigmeT123  thanks for mentioning those details about PR . Actually I am new to web development and implemented all that I can to the best of it , Can you please mention what kind of changes are you requesting hence I can learn those and start implementing ASAP ,PS thank you so much for guiding me as this is my first PR :)

**Comment by JigmeT123** [comment]
> Hey @JigmeT123  thanks for mentioning those details about PR . Actually I am new to web development and implemented all that I can to the best of it , Can you please mention what kind of changes are you requesting hence I can learn those and start implementing ASAP ,PS thank you so much for guiding me as this is my first PR :)

Sure I will be more than happy to help you. Can you try to build contact us from scratch instead of reusing what's already there. 

You can use any library that you want. You can try to include validation. You can use library such as formik or any other if you don't want to build it from scratch.

**Comment by DADDY-DOUBLESHOT** [comment]
Sure I will give it a try and will update it by EOD.

**Comment by DADDY-DOUBLESHOT** [comment]
Hey @JigmeT123  I was not able to make major UI changes but I worked on following features
features added --
>Form Validations on Name and email and message
>Pattern Matching provided with validations
>React-hook-form and toast container added
> provided small acknowledgement on form submission.

I hope my PR get accepted thankyou

**Comment by JigmeT123** [comment]
Job well done. Can you resolve the conflict. Then you are done

**Comment by JigmeT123** [comment]
> Hey @JigmeT123 I was not able to make major UI changes but I worked on following features features added --
> 
> > Form Validations on Name and email and message
> > Pattern Matching provided with validations
> > React-hook-form and toast container added
> > provided small acknowledgement on form submission.
> 
> I hope my PR get accepted thankyou

Approved. Thank you for your contribution.

**Pull request merged**
